# Generated by Django 5.2.14 on 2026-05-14 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='role',
        ),
        migrations.DeleteModel(
            name='ColumnPermission',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
