# Generated by Django 5.2.11 on 2026-05-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktrax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_worker',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
