# Generated by Django 5.2.11 on 2026-05-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktrax', '0002_alter_type_worker_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='nom',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
