export const ROLES = {
  Administrateur: {
    initials: 'A',
    name: 'Administrateur',
    subtitle: 'Administrateur',
    accent: '#f97316',
    defaultPage: 'dashboard',
    nav: [
      { section: 'Pilotage' },
      { id: 'dashboard', icon: '📊', label: 'Tableau de bord' },
      { id: 'workers', icon: '👷', label: 'Ouvriers' },
      { id: 'engines', icon: '🚜', label: 'Engins' },
      { id: 'attendance', icon: '📍', label: 'Pointage' },
      { id: 'fuel', icon: '⛽', label: 'Carburant' },
      { section: 'Gestion' },
      { id: 'absences', icon: '📅', label: 'Absences & Congés' },
      { id: 'payroll', icon: '💰', label: 'Paie' },
      { id: 'cameras', icon: '📹', label: 'Caméras' },
      { id: 'reports', icon: '📈', label: 'Rapports' },
      { section: 'Administration' },
      { id: 'users', icon: '👥', label: 'Utilisateurs' },
    ],
  },
  RH: {
    initials: 'SR',
    name: 'Sarah RH',
    subtitle: 'Ressources Humaines',
    accent: '#8b5cf6',
    defaultPage: 'hr-dashboard',
    nav: [
      { section: 'Ressources Humaines' },
      { id: 'hr-dashboard', icon: '🧑‍💼', label: 'Espace RH' },
      { id: 'workers', icon: '👷', label: 'Ouvriers' },
      { id: 'absences', icon: '📅', label: 'Absences & Congés' },
      { id: 'payroll', icon: '💰', label: 'Paie' },
    ],
  },
  Superviseur: {
    initials: 'MS',
    name: 'Marc Superviseur',
    subtitle: 'Superviseur',
    accent: '#2563a8',
    defaultPage: 'supervisor-dashboard',
    nav: [
      { section: 'Mon chantier' },
      { id: 'supervisor-dashboard', icon: '👷', label: 'Mon chantier' },
      { id: 'workers', icon: '👷', label: 'Ouvriers' },
      { id: 'engines', icon: '🚜', label: 'Engins' },
      { id: 'attendance', icon: '📍', label: 'Pointage' },
      { id: 'cameras', icon: '📹', label: 'Caméras' },
    ],
  },
  Contrôleur: {
    initials: 'KA',
    name: 'Kofi Akuetteh',
    subtitle: 'Contrôleur',
    accent: '#0f766e',
    defaultPage: 'controller-terminal',
    nav: [
      { section: 'Pointage' },
      { id: 'controller-terminal', icon: '📱', label: 'Terminal pointage' },
      { id: 'controller-journal', icon: '📋', label: 'Journal du jour' },
    ],
  },
  Pompiste: {
    initials: 'AS',
    name: 'Ama Sodzi',
    subtitle: 'Pompiste',
    accent: '#f97316',
    defaultPage: 'pompiste-terminal',
    nav: [
      { section: 'Distribution' },
      { id: 'pompiste-terminal', icon: '⛽', label: 'Terminal carburant' },
      { id: 'pompiste-history', icon: '📊', label: 'Rapport conso.' },
    ],
  },
};

export const PAGE_TITLES = {
  dashboard: 'Tableau de bord',
  workers: 'Ouvriers',
  engines: 'Engins',
  attendance: 'Pointage biométrique',
  fuel: 'Carburant',
  cameras: 'Caméras IP',
  absences: 'Absences & Congés',
  payroll: 'Paie',
  reports: 'Rapports',
  users: 'Gestion des utilisateurs',
  'hr-dashboard': 'Ressources Humaines',
  'supervisor-dashboard': 'Mon chantier',
  'controller-terminal': 'Terminal Contrôleur',
  'controller-journal': 'Journal du jour',
  'pompiste-terminal': 'Terminal Pompiste',
  'pompiste-history': 'Rapport consommation',
};
